apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleproject1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleproject1
  template:
    metadata:
      labels:
        app: exampleproject1
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: exampleproject1
          image: dockerregistry.dev.bitsandlikes.com/exampleproject1:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
      restartPolicy: Always